# ====================================================
# Viostream JS package workflow
# ====================================================

name: Package

on:
  push:
    branches:
      - main

jobs:
  publish:
    name: Publish a new version to Github package registry
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - id: tag
        uses: Viostream/github-tag-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: npm install
      - uses: JS-DevTools/npm-publish@v1
        with:
          registry: https://npm.pkg.github.com
          tag: ${{ steps.tag.outputs.new_tag }}
          token: ${{ secrets.GITHUB_TOKEN }}
  npm_audit:
    name: dependency audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: npm audit
        run: |
          npm audit --production
