# ====================================================
# Viostream JS package workflow
# ====================================================

name: Package

on:
  push:
    branches:
      - main

jobs:
  publish:
    name: Publish a new version to Github package registry
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - id: tag
        uses: Viostream/github-tag-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          echo "writing tag"
          sed -i 's/"version": ".*",$/"version": "${{ secrets.GITHUB_TOKEN }}",/' package.json
      - run: npm install
      - uses: JS-DevTools/npm-publish@v1
        with:
          registry: https://npm.pkg.github.com
          token: ${{ secrets.GITHUB_TOKEN }}
